name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.8

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  postgres: ^3.0.0
  minio_new: ^1.0.1
  dotenv: ^4.2.0
  dart_jsonwebtoken: ^2.7.2
  crypto: ^3.0.3
  mime: ^1.0.6
  http_parser: ^4.1.2
  shelf_multipart: ^1.0.0


dev_dependencies:
  http: ^0.13.6
  lints: ^6.0.0
  test: ^1.25.6
